# Conversion to YAML from Properties formar report
# Warnings:
# - The yaml file had comments which are lost in the refactoring!
# - 'org.nit.favColor' has some entries that look like list items and others that look like map entries. All these entries are treated as map entries!
spring:
  application:
    name: BootProj08-Data-Bluck-Injuection-Configuraction-Array-list-set-map
org:
  nit:
    eno: 101
    name: NIT
    favColor:
      - Pink
      - Red
      - Blue
    nickname:
     - bata
     - lala
     - babu
    mobilno: 9999999999,2222222222,4444444444,9999999999
    idDetails:
      addharcard: 223344553344
      pancard: 34hdfd43v
      idcard: 4444422
    company:
       name: Rama
       age: 23
       size: 33
